FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && \
    apt-get install -y gcc libpq-dev && \
    pip install psycopg2 && \
    apt-get remove -y gcc && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

CMD ["python", "load_csv_to_postgres.py"]
